The birth date can be extracted also from bis numbers
Moeriki/be-nrn pull request #5
Opened 2020-07-09 09:16 UTC by shkurata

It will be a good feature if it accepts also BIS numbers

2020-07-09 10:10 UTC, Moeriki commented
What is a BIS number?

2020-07-09 11:00 UTC, shkurata commented
Een eerste groep van zes cijfers, gevormd door de geboortedatum in de volgorde: jaar, maand, dag. Maand en/of dag kunnen nul zijn indien de exacte geboortedatum niet bekend is. Indien de persoon niet ingeschreven is in het Rijksregister, maar er toch gegevens moeten worden bijgehouden voor de sociale zekerheid, bijvoorbeeld buitenlandse werknemers die minder dan drie maanden in België verblijven of grensarbeiders, dan wordt een bisnummer toegekend. Bij het bisnummer wordt de geboortemaand verhoogd met 20 of 40. Als bij de aanvraag het geslacht bekend is, wordt de geboortemaand verhoogd met 40, anders wordt ze verhoogd met 20. Indien de persoon vluchteling is en de geboortedatum niet gekend is, wordt de geboortemaand op 00 gezet en de geboortedag op 00 gezet.
https://nl.m.wikipedia.org/wiki/Rijksregisternummer

2020-07-10 07:44 UTC, Moeriki commented
Just FYI. It's better to open an issue first so we can discuss things.

If we are going to add BIS numbers we want to add also some additional functions in regard. I propose the following.

`isBisNumber()`: returns `true` if birth month was increased with `20` or `40`.
`isBisBirthdateKnown()` returns `true` if birth month `>0` after subtracting `20` or `40`.
`isBisGenderKnown()` returns `true` if birth month was increased with `40`.
`isNrnNumber()`: returns `true` if birth month was not increased with `20` or `40`.

Additionally I think the following changes are in order.

`getBirthDate()` should throw an Error if the birth date is unknown. We can't be ambiguous about this.

2020-07-10 07:50 UTC, Moeriki commented
We have an return interface on `parse()` we should probably update.

https://github.com/Moeriki/be-nrn/blob/master/src/index.ts#L8

```ts
export interface Nrn {
  birthDate: readonly [string, string, string];
  serial: string;
  checksum: string;
}
```

So we can include the slicing of the date parts in the `parse` already.

2020-07-10 07:53 UTC, Moeriki commented
It doesn't seem like you ran linting. Make sure to run prettier when you are done.

2020-07-10 10:45 UTC, moeriki requested changes

2020-07-10 10:45 UTC, moeriki commented on src/index.spec.ts
> +  it('should extract the correct birthdate from a NRN', () => {
Can you pad an empty line before and after this test like the rest of the file.

2020-07-10 10:45 UTC, moeriki commented on src/index.ts
> +  const day = Number(birthDate.slice(4, 6)) || 1; // Eg. 14 from '860814'
Why `|| 1`?

As I understood it some people can have `00` as birth month. I think it's better to throw an error in that case. Returning a `Date` for them would be ambiguous.

2020-07-10 10:45 UTC, moeriki commented on src/index.ts
> +}
Let's not have this in a separate function. We will need to re-use its logic many times though.

2020-07-10 10:49 UTC, shkurata commented on src/index.ts
> +  const day = Number(birthDate.slice(4, 6)) || 1; // Eg. 14 from '860814'
Some people can have 00 for the birth month and also 00 for the birth date, so we decided to use the middle of the year and  the first of the month.

2020-07-10 10:50 UTC, shkurata commented
We had to find a fast solution, because we had an issue in PROD.

2020-07-10 14:32 UTC, Moeriki commented on src/index.ts
> +  const day = Number(birthDate.slice(4, 6)) || 1; // Eg. 14 from '860814'
Yeah so I don't want that. You can't tell the difference between known and unknown dates. Just throw an error and resolve it in your own application. It doesn't make sense for the library to make these kinds of defaults.

2020-08-20 14:20 UTC, merged

2020-08-20 15:51 UTC, Moeriki commented
Merged and optimised.

I renamed a few methods.

`isBisBirthdateKnown` -> `isBirthDateKnown`
`isBisGenderKnown` -> `isGenderKnown`

They now work regardless of BIS / NRN.

I removed `isValidNrnNumber` because this is an opinionated implementation. Being "valid" is not something I aim to solve in the library..
I fixed one bug in your implementation where `isGenderKnown()` didn't return `trye` if the gender was known but the date of birth was not.

```js
    expect(nrnUtils.isGenderKnown('814000 896 60')).toBe(true);
```

This is published a `be-nrn@1.1.2`.